### ISSUE TITLE
Image.ANTIALIAS is not a valid property

### ISSUE THREAD

**Issue by dakotacookenmaster** [JesseHines0/ShellAdventure#3]
In the `main.py` file, Image.ANTIALIAS is used as an argument on line 77. That property does not seem to exist. Modifying this to be `Image.ADAPTIVE` seems to allow the program to resume normal operation.

**Comment by jesse-r-s-hines** [comment]
Thanks! I've pushed a fix for this, and froze the pip dependencies so things like this should be less likely to crop up in the future.
